version: 46
jobs:
  - name: build and publish docker
    steps:
      - type: CheckoutStep
        name: checkout code
        cloneCredential:
          type: DefaultCredential
        withLfs: false
        withSubmodules: false
        condition: SUCCESSFUL
        optional: false
      - type: BuildImageStep
        name: build and push docker image
        output:
          type: RegistryOutput
          tags: "@server@/unnamed-group/express.unnamed.group/express.unnamed.group:@branch@"
        registryLogins:
          - registryUrl: "@server@"
            userName: zuedev
            passwordSecret: PackageWriterToken
        condition: SUCCESSFUL
        optional: false
    triggers:
      - type: BranchUpdateTrigger
        userMatch: anyone
    retryCondition: never
    maxRetries: 3
    retryDelay: 30
    timeout: 14400
