services:
  174bg-net:
    build: https://github.com/zuedev/unnamed-group.git#master:communities/red-right-hand/174bg.net
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
      - "3000:3000/udp"
    env_file: 174bg-net.env # we don't include this file for obvious reasons, but it should contain the necessary environment variables for the application to run
