export const ROLES = [
    {
        branch: "Naval",
        value: "Ship Captain",
        text: "Ship Captain",
        link: "https://handbook.174bg.net/#ship-captain",
    },
    {
        branch: "Naval",
        value: "Pilot",
        text: "Pilot",
        link: "https://handbook.174bg.net/#pilot",
    },
    {
        branch: "Naval",
        value: "Helmsman",
        text: "Helmsman",
        link: "https://handbook.174bg.net/#helmsman",
    },
    {
        branch: "Naval",
        value: "Gunner",
        text: "Gunner",
        link: "https://handbook.174bg.net/#gunner",
    },
    {
        branch: "Marine",
        value: "Tactical Marine",
        text: "Tactical Marine",
        link: "https://handbook.174bg.net/#tactical-marine",
    },
    {
        branch: "Marine",
        value: "Heavy Marine",
        text: "Heavy Marine",
        link: "https://handbook.174bg.net/#heavy-marine",
    },
    {
        branch: "Marine",
        value: "Scout Marine",
        text: "Scout Marine",
        link: "https://handbook.174bg.net/#scout-marine",
    },
    {
        branch: "Marine",
        value: "Combat Medic",
        text: "Combat Medic",
        link: "https://handbook.174bg.net/#combat-medic",
    },
    {
        branch: "Marine",
        value: "Combat Engineer",
        text: "Combat Engineer",
        link: "https://handbook.174bg.net/#combat-engineer",
    },
    {
        branch: "Marine",
        value: "Warden",
        text: "Warden",
        link: "https://handbook.174bg.net/#warden",
    },
    {
        branch: "Auxiliary",
        value: "Engineer",
        text: "Engineer",
        link: "https://handbook.174bg.net/#engineer",
    },
    {
        branch: "Auxiliary",
        value: "Hazardous Materials Specialist",
        text: "Hazardous Materials Specialist",
        link: "https://handbook.174bg.net/#hazardous-materials-specialist",
    },
    {
        branch: "Auxiliary",
        value: "Medical Doctor",
        text: "Medical Doctor",
        link: "https://handbook.174bg.net/#medical-doctor",
    },
    {
        branch: "Auxiliary",
        value: "Quartermaster",
        text: "Quartermaster",
        link: "https://handbook.174bg.net/#quartermaster",
    },
    {
        branch: "Auxiliary",
        value: "Cargo Technician",
        text: "Cargo Technician",
        link: "https://handbook.174bg.net/#cargo-technician",
    },
    {
        branch: "Auxiliary",
        value: "Craftsman",
        text: "Craftsman",
        link: "https://handbook.174bg.net/#craftsman",
    },
    {
        branch: "Auxiliary",
        value: "Mining Technician",
        text: "Mining Technician",
        link: "https://handbook.174bg.net/#mining-technician",
    },
    {
        branch: "Auxiliary",
        value: "Salvage Operator",
        text: "Salvage Operator",
        link: "https://handbook.174bg.net/#salvage-operator",
    },
    {
        branch: "Auxiliary",
        value: "Expeditionary Analyst",
        text: "Expeditionary Analyst",
        link: "https://handbook.174bg.net/#expeditionary-analyst",
    },
    {
        branch: "Auxiliary",
        value: "Intelligence Agent",
        text: "Intelligence Agent",
        link: "https://handbook.174bg.net/#intelligence-agent",
    },
];

export const RANK_NAMES = {
    Naval: ["Cadet", "Ensign", "Lieutenant", "Captain", "Commodore", "Admiral"],
    Marine: [
        "Private",
        "Corporal",
        "Sergeant",
        "Major",
        "Commander",
        "General",
    ],
    Auxiliary: [
        "Trainee",
        "Technician",
        "Specialist",
        "Supervisor",
        "Chief",
        "Marshal",
    ],
};
